### Attributes
# 
# instagram_username    The users instagram screename
# email                 Optional attribute
# api_token             Generated by `generate_api_token
# access_token          Oauth token returned by Instagram
#
class User < ActiveRecord::Base
  before_create :generate_api_token

  protected
  def generate_api_token
    self.api_token = Base64.urlsafe_encode64(SecureRandom.urlsafe_base64(128) + "#{Time.now.to_f*1000}")
  end
end
